### ISSUE TITLE
No obvious documentation for recognizing a rule with an epsilon/empty string as a terminal.

### ISSUE THREAD

**Issue by Reisande** [rodolf0/tox#3]
I am using this crate for a project I am building, but I have some trouble. I was building a simple example of a context free grammar, but I ran into a problem: there is no obvious way to build a grammar which has an epsilon as a rule.

**Comment by Reisande** [comment]
Specifically within the earlgrey module.

**Comment by rodolf0** [comment]
Hi @Reisande, you can specify an epsilon rule like

```
    let g = earlgrey::GrammarBuilder::default()
      .nonterm("S")
      .rule("S", &[])
      .into_grammar("S")
      .unwrap();
```

Note that you can also use the `abackus` crate which wraps earlgrey so that you can specify your grammar as a string instead (check the [example](https://github.com/rodolf0/tox/tree/master/abackus)).

If you want to use earlgrey directly here's another [example for an epsilon rule](https://github.com/rodolf0/tox/blob/master/abackus/src/ebnf.rs#L221-L232) from the abackus crate itself.
